### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by ReinforceZwei** [ReinforceZwei/anime-list-next#1]
- [ ] login/form submit loading button
- [ ] poster fullscreen
- [ ] copy name button
- [ ] edit form disable save if not dirty
- [ ] edit form disable backdrop close if dirty
- [ ] add anime search tmdb + save id
- [ ] Chip default light/dark mode color for delete icon
